### ISSUE TITLE
HA GUI Screenshots

### ISSUE THREAD

**Issue by tatunts** [skalavala/smarthome#30]
Hello my friend, how are you today?

Great job sharing your setup on GitHub, it helped me a lot!

May I ask you something? How do you took your screenshots of the entire page of your HA GUI?

I use Windows and Chrome and had tested many screen grab addons but they always cut the image half way...

Thanks!

**Comment by poldim** [comment]
http://bfy.tw/GcvH

**Comment by skalavala** [comment]
@tatunts Thank you! I used Adobe Photoshop - basically took a bunch of screen shots and merged them to make it look like one long page/screen... I even had to cheat the scroll bar - because in every screen shot, you will find the scroll bar at a different place, and did some work when merging, so that you see the scroll bar position in only one page 😄
