### ISSUE TITLE
Life360 errors

### ISSUE THREAD

**Issue by aetolus** [skalavala/smarthome#31]
Hey Suresh,

I've been using your Life360 component for some time, but have just noticed the following cropping up in the last day or so:

`Life360 has not responsed well. Nothing to worry, will try again!`

And not publishing any MQTT results etc.

Are you aware of any changes to Life360 API that have been made that could cause this?

Cheers!

Edit: I should mention the app is still working OK, and I've confirmed the username/password are working without error.

**Comment by skalavala** [comment]
Hi there,

Once in a while the Life360 servers get busy and fail to serve the requests. When that happens you get that error, that says, `Life360 has not responsed well. Nothing to worry, will try again!`. You should worry if you do not see any data.

The other day someone had trouble with the component, and it turned out the password has some special characters that was breaking the curl/shell command. If you only get one or two a day, you shouldn't be worried. I get them too 😄

**Comment by aetolus** [comment]
Thanks for responding.

I was actually getting them for over a day! But must have been some localised issue, because I've just checked and it's all good again now. Cheers!
